# Generated by Django 5.2.3 on 2025-06-29 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
